//
// ResearchAssistant.ts
//
// Rueter AI — Pipelines
//
// Produces a complete, well-structured research document on any topic,
// with section-by-section writing and a quality-driven revision pass.
//

import * as nodePath from "node:path"

import {
    instantiateSpecialPreset,
    PromptEnhancerPreset,
    SelfCritiquePreset,
    AcademicWriterPreset,
    ResearchOutlinerPreset,
} from "../classes/SpecialModels.js"

import {
    ask, askForJson, extractCritiqueScore, log, timestamp,
    writeFileSafe,
    type ProgressCallback,
} from "./_shared.js"

// ─── Config ───────────────────────────────────────────────────────────────────

export interface ResearchAssistantConfig {
    /** xAI API key */
    apiKey: string
    /** Research topic or question */
    topic: string
    /** Path to save the research document (default: ./RueterResearch.md) */
    outputPath?: string
    /** Number of body sections, not counting intro/conclusion (default: 4) */
    sections?: number
    /** Called after each step with a status message */
    onProgress?: ProgressCallback
}

// ─── Internal Types ───────────────────────────────────────────────────────────

interface ResearchSection {
    heading: string
    key_points: string[]
}

interface ResearchOutline {
    title: string
    abstract: string
    sections: ResearchSection[]
}

// ─── Prompt & Document Builders ───────────────────────────────────────────────

function buildSectionPrompt(
    outline: ResearchOutline,
    section: ResearchSection,
    sectionIndex: number,
    totalSections: number,
    previousContent: string
): string {
    const contextNote = previousContent.length > 0
        ? `\nPAPER SO FAR (for continuity — do not repeat, just continue):\n${"─".repeat(60)}\n${previousContent.slice(-3000)}\n${"─".repeat(60)}\n`
        : ""
    return [
        `PAPER TITLE: "${outline.title}"`,
        `ABSTRACT: ${outline.abstract}`,
        `SECTION ${sectionIndex + 1} OF ${totalSections}: "${section.heading}"`,
        contextNote,
        "This section must address the following points:",
        section.key_points.map(p => `  • ${p}`).join("\n"),
        "",
        `Write the complete "${section.heading}" section in full academic prose.`,
        `Begin with: ## ${section.heading}`,
    ].join("\n")
}

function buildResearchMd(outline: ResearchOutline, sections: string[]): string {
    return [
        `# ${outline.title}`,
        `> Generated by Rueter AI Research Assistant · ${timestamp()}`,
        "", "## Abstract", outline.abstract,
        "", "---", "",
        ...sections,
        "", "---",
        "*Generated by Rueter AI · ResearchAssistantWorkflow*",
    ].join("\n")
}

// ─── Workflow ─────────────────────────────────────────────────────────────────

/**
 * Produces a complete, well-structured research document on any topic.
 *
 * Pipeline:
 *   1. Enhance topic → PromptEnhancerPreset
 *   2. Generate JSON outline → ResearchOutlinerPreset
 *   3. Write each section sequentially with rolling context → AcademicWriterPreset
 *   4. Critique the full paper → SelfCritiquePreset
 *   5. Revision pass on all sections if quality score < 7 → AcademicWriterPreset
 */
export async function ResearchAssistantWorkflow(config: ResearchAssistantConfig): Promise<string> {
    const {
        apiKey,
        topic,
        outputPath = nodePath.join(process.cwd(), "RueterResearch.md"),
        sections   = 4,
        onProgress,
    } = config

    const enhancer  = instantiateSpecialPreset(apiKey, PromptEnhancerPreset)
    const outliner  = instantiateSpecialPreset(apiKey, ResearchOutlinerPreset)
    const writer    = instantiateSpecialPreset(apiKey, AcademicWriterPreset)
    const critiquer = instantiateSpecialPreset(apiKey, SelfCritiquePreset)

    // 1 ─ Enhance topic
    log(onProgress, "Step 1/5 — Enhancing research topic…")
    const enhancedTopic = await ask(
        enhancer,
        `Transform this into a precise, well-scoped academic research topic suitable for a ${sections + 2}-section paper: ${topic}`
    )

    // 2 ─ Generate JSON outline
    log(onProgress, "Step 2/5 — Generating research outline…")
    const outline = await askForJson<ResearchOutline>(
        outliner,
        `Generate a research paper outline for the following topic. Include exactly ${sections + 2} sections (Introduction + ${sections} body sections + Conclusion).\n\nTopic: ${enhancedTopic}`
    )

    if (!Array.isArray(outline.sections) || outline.sections.length === 0) {
        throw new Error("ResearchOutlinerPreset returned an outline with no sections.")
    }

    log(onProgress, `  Outline: "${outline.title}" · ${outline.sections.length} sections`)

    // 3 ─ Write each section with rolling context, saving after each one
    log(onProgress, `Step 3/5 — Writing ${outline.sections.length} sections…`)

    const writtenSections: string[] = []

    for (let i = 0; i < outline.sections.length; i++) {
        const section = outline.sections[i]
        log(onProgress, `  [${i + 1}/${outline.sections.length}] Writing "${section.heading}"…`)

        const content = await ask(
            writer,
            buildSectionPrompt(outline, section, i, outline.sections.length, writtenSections.join("\n\n"))
        )

        writtenSections.push(content)
        await writeFileSafe(outputPath, buildResearchMd(outline, writtenSections))
    }

    // 4 ─ Critique the full paper
    log(onProgress, "Step 4/5 — Evaluating paper quality…")
    const critique = await ask(critiquer, `Critique this academic paper:\n\n${writtenSections.join("\n\n")}`)
    const score    = extractCritiqueScore(critique)
    log(onProgress, `  Quality score: ${score}/10`)

    // 5 ─ Revision pass if quality is below threshold
    if (score < 7) {
        log(onProgress, "Step 5/5 — Revising underperforming sections…")

        for (let i = 0; i < outline.sections.length; i++) {
            const section = outline.sections[i]
            writtenSections[i] = await ask(writer, [
                `The following section of a research paper received a low overall quality score (${score}/10).`,
                `Paper title: "${outline.title}"`,
                "", `SECTION: "${section.heading}"`,
                writtenSections[i],
                "", "Overall paper critique for context:", critique,
                "", `Now rewrite the "${section.heading}" section. Begin with: ## ${section.heading}`,
            ].join("\n"))
        }

        await writeFileSafe(outputPath, buildResearchMd(outline, writtenSections))
        log(onProgress, "  Revision complete.")
    } else {
        log(onProgress, "Step 5/5 — Paper quality is high; no revision needed.")
    }

    const finalDocument = buildResearchMd(outline, writtenSections)
    await writeFileSafe(outputPath, finalDocument)

    log(onProgress, `\n✅ Done — research document saved to ${outputPath}`)
    return finalDocument
}
