//
// Provider Models
//
// Rueter AI
// created by Aaron Meche
//
// Catalog scope:
// - Text-generation model IDs that fit Rueter's current prompt interfaces.
// - Audio-only, image-only, realtime-only, and generation-only models are excluded.
// - Pricing is included when it was verifiable from current official docs. When current
//   docs exposed capabilities and IDs but not stable crawlable pricing, pricing is marked
//   unavailable so cost tracking can safely return null instead of misleading numbers.
//

import type { ModelConfigSupport, ModelInfo, Models } from "../types.js"

const ANTHROPIC_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    top_k: true,
    stop_sequences: true,
})

const OPENAI_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    frequency_penalty: true,
    presence_penalty: true,
    stop_sequences: true,
    n: true,
})

const GEMINI_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    top_k: true,
    stop_sequences: true,
    n: true,
})

const GROK_REASONING_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    n: true,
})

const GROK_NON_REASONING_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    frequency_penalty: true,
    presence_penalty: true,
    stop_sequences: true,
    n: true,
})

const DEEPSEEK_CHAT_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    frequency_penalty: true,
    presence_penalty: true,
    stop_sequences: true,
})

const DEEPSEEK_REASONER_CONFIG_SUPPORT = createConfigSupport({
    system_prompt: true,
    temperature: true,
    max_tokens: true,
    top_p: true,
    stop_sequences: true,
})

const providerModelsByName: Models = {
    anthropic: [
        createModel({
            name: "claude-haiku-4-5-20251001",
            display_name: "Claude Haiku 4.5",
            family: "Claude 4.5",
            description: "Fastest Claude model with near-frontier intelligence for high-volume work.",
            status: "active",
            release_stage: "stable",
            aliases: ["claude-haiku-4-5"],
            input_cost: 1.00,
            output_cost: 5.00,
            context: 200_000,
            max_output_tokens: 64_000,
            knowledge_cutoff: "2025-02",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "claude-sonnet-4-6",
            display_name: "Claude Sonnet 4.6",
            family: "Claude 4.6",
            description: "Best Anthropic price-performance balance for coding, analysis, and agents.",
            status: "active",
            release_stage: "stable",
            input_cost: 3.00,
            output_cost: 15.00,
            context: 1_000_000,
            max_output_tokens: 64_000,
            knowledge_cutoff: "2025-08",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "claude-opus-4-7",
            display_name: "Claude Opus 4.7",
            family: "Claude 4.7",
            description: "Most capable generally available Claude model for complex reasoning and coding.",
            status: "active",
            release_stage: "stable",
            input_cost: 5.00,
            output_cost: 25.00,
            context: 1_000_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2026-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "claude-opus-4-6",
            display_name: "Claude Opus 4.6",
            family: "Claude 4.6",
            description: "Previous Opus flagship with 1M context and higher max output than Sonnet.",
            status: "active",
            release_stage: "stable",
            input_cost: 5.00,
            output_cost: 25.00,
            context: 1_000_000,
            max_output_tokens: 128_000,
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
        }),
        createModel({
            name: "claude-sonnet-4-5-20250929",
            display_name: "Claude Sonnet 4.5",
            family: "Claude 4.5",
            description: "Previous Sonnet release with strong speed-intelligence balance.",
            status: "active",
            release_stage: "stable",
            aliases: ["claude-sonnet-4-5"],
            input_cost: 3.00,
            output_cost: 15.00,
            context: 1_000_000,
            max_output_tokens: 64_000,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
        }),
        createModel({
            name: "claude-opus-4-1-20250805",
            display_name: "Claude Opus 4.1",
            family: "Claude 4.1",
            description: "Legacy Opus 4.1 release still listed as active in Anthropic deprecation docs.",
            status: "active",
            release_stage: "stable",
            input_cost: 15.00,
            output_cost: 75.00,
            context: 200_000,
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
        }),
        createModel({
            name: "claude-opus-4-20250514",
            display_name: "Claude Opus 4",
            family: "Claude 4",
            description: "Deprecated Claude 4 Opus release kept for catalog completeness.",
            status: "deprecated",
            release_stage: "deprecated",
            input_cost: 15.00,
            output_cost: 75.00,
            context: 200_000,
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2026-06-15",
        }),
        createModel({
            name: "claude-sonnet-4-20250514",
            display_name: "Claude Sonnet 4",
            family: "Claude 4",
            description: "Deprecated Claude 4 Sonnet release kept for catalog completeness.",
            status: "deprecated",
            release_stage: "deprecated",
            input_cost: 3.00,
            output_cost: 15.00,
            context: 200_000,
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2026-06-15",
        }),
        createModel({
            name: "claude-3-7-sonnet-20250219",
            display_name: "Claude Sonnet 3.7",
            family: "Claude 3.7",
            description: "Retired Claude 3.7 Sonnet release retained as historical catalog metadata.",
            status: "retired",
            release_stage: "retired",
            input_cost: 3.00,
            output_cost: 15.00,
            context: 200_000,
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2026-02-19",
        }),
        createModel({
            name: "claude-3-5-sonnet-20241022",
            display_name: "Claude Sonnet 3.5 (2024-10-22)",
            family: "Claude 3.5",
            description: "Retired Claude 3.5 Sonnet snapshot.",
            status: "retired",
            release_stage: "retired",
            input_cost: 3.00,
            output_cost: 15.00,
            context: 200_000,
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2025-10-28",
        }),
        createModel({
            name: "claude-3-5-sonnet-20240620",
            display_name: "Claude Sonnet 3.5 (2024-06-20)",
            family: "Claude 3.5",
            description: "Original Claude 3.5 Sonnet snapshot.",
            status: "retired",
            release_stage: "retired",
            input_cost: 3.00,
            output_cost: 15.00,
            context: 200_000,
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2025-10-28",
        }),
        createModel({
            name: "claude-3-5-haiku-20241022",
            display_name: "Claude Haiku 3.5",
            family: "Claude 3.5",
            description: "Retired Haiku 3.5 release.",
            status: "retired",
            release_stage: "retired",
            input_cost: 0.80,
            output_cost: 4.00,
            context: 200_000,
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2026-02-19",
        }),
        createModel({
            name: "claude-3-opus-20240229",
            display_name: "Claude Opus 3",
            family: "Claude 3",
            description: "Retired Claude 3 Opus release.",
            status: "retired",
            release_stage: "retired",
            input_cost: 15.00,
            output_cost: 75.00,
            context: 200_000,
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2026-01-05",
        }),
        createModel({
            name: "claude-3-haiku-20240307",
            display_name: "Claude Haiku 3",
            family: "Claude 3",
            description: "Retired Claude 3 Haiku release.",
            status: "retired",
            release_stage: "retired",
            input_cost: 0.25,
            output_cost: 1.25,
            context: 200_000,
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["messages"],
            config_support: ANTHROPIC_CONFIG_SUPPORT,
            retirement_date: "2026-04-20",
        }),
    ],
    openai: [
        createModel({
            name: "gpt-5.4-nano",
            display_name: "GPT-5.4 nano",
            family: "GPT-5.4",
            description: "Cheapest GPT-5.4-class model for simple, high-volume workloads.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-5.4-nano-2026-03-17"],
            input_cost: 0.20,
            output_cost: 1.25,
            cached_input_cost: 0.02,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gpt-5.4-mini",
            display_name: "GPT-5.4 mini",
            family: "GPT-5.4",
            description: "Strong mini model for coding, subagents, and cost-sensitive agent loops.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-5.4-mini-2026-03-17"],
            input_cost: 0.75,
            output_cost: 4.50,
            cached_input_cost: 0.075,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gpt-5.4",
            display_name: "GPT-5.4",
            family: "GPT-5.4",
            description: "Current frontier GPT model for complex professional work and coding.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-5.4-2026-03-05"],
            input_cost: 2.50,
            output_cost: 15.00,
            cached_input_cost: 0.25,
            context: 1_050_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gpt-5.4-pro",
            display_name: "GPT-5.4 pro",
            family: "GPT-5.4",
            description: "Highest-compute GPT-5.4 variant for smartest and most precise responses.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-5.4-pro-2026-03-05"],
            input_cost: 30.00,
            output_cost: 180.00,
            context: 1_050_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: false,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
            current: true,
        }),
        createModel({
            name: "gpt-5.3-codex",
            display_name: "GPT-5.3-Codex",
            family: "GPT-5 Codex",
            description: "Current flagship OpenAI coding model for long-horizon, agentic software work.",
            status: "active",
            release_stage: "stable",
            input_cost: 1.75,
            output_cost: 14.00,
            cached_input_cost: 0.175,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gpt-5-nano",
            display_name: "GPT-5 nano",
            family: "GPT-5",
            description: "Previous GPT-5 nano release retained for compatibility.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5-nano-2025-08-07"],
            input_cost: 0.05,
            output_cost: 0.40,
            cached_input_cost: 0.005,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-05-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5-mini",
            display_name: "GPT-5 mini",
            family: "GPT-5",
            description: "Previous GPT-5 mini release for low-latency, high-volume tasks.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5-mini-2025-08-07"],
            input_cost: 0.25,
            output_cost: 2.00,
            cached_input_cost: 0.025,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-05-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5",
            display_name: "GPT-5",
            family: "GPT-5",
            description: "Previous GPT-5 flagship reasoning model.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5-2025-08-07"],
            input_cost: 1.25,
            output_cost: 10.00,
            cached_input_cost: 0.125,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.2",
            display_name: "GPT-5.2",
            family: "GPT-5.2",
            description: "Previous frontier GPT-5.2 release for complex professional work.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5.2-2025-12-11"],
            input_cost: 1.75,
            output_cost: 14.00,
            cached_input_cost: 0.175,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.2-codex",
            display_name: "GPT-5.2-Codex",
            family: "GPT-5 Codex",
            description: "Previous frontier Codex model optimized for long-horizon agentic coding.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 1.75,
            output_cost: 14.00,
            cached_input_cost: 0.175,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.2-pro",
            display_name: "GPT-5.2 pro",
            family: "GPT-5.2",
            description: "Previous pro GPT model with much higher compute per request.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5.2-pro-2025-12-11"],
            input_cost: 21.00,
            output_cost: 168.00,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2025-08-31",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: false,
            tool_use: true,
            prompt_caching: false,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.1",
            display_name: "GPT-5.1",
            family: "GPT-5.1",
            description: "Earlier GPT-5 family flagship for coding and agentic tasks.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5.1-2025-11-13"],
            input_cost: 1.25,
            output_cost: 10.00,
            cached_input_cost: 0.125,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.1-codex-max",
            display_name: "GPT-5.1-Codex-Max",
            family: "GPT-5 Codex",
            description: "Higher-end GPT-5.1 Codex variant optimized for long-running coding tasks.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 1.25,
            output_cost: 10.00,
            cached_input_cost: 0.125,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.1-codex",
            display_name: "GPT-5.1 Codex",
            family: "GPT-5 Codex",
            description: "Earlier GPT-5.1-based Codex model for agentic coding tasks.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 1.25,
            output_cost: 10.00,
            cached_input_cost: 0.125,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5.1-codex-mini",
            display_name: "GPT-5.1 Codex mini",
            family: "GPT-5 Codex",
            description: "Smaller GPT-5.1 Codex variant for cheaper coding and subagent workloads.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 0.25,
            output_cost: 2.00,
            cached_input_cost: 0.025,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5-pro",
            display_name: "GPT-5 pro",
            family: "GPT-5",
            description: "Higher-compute GPT-5 pro model for tougher reasoning requests.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gpt-5-pro-2025-10-06"],
            input_cost: 15.00,
            output_cost: 120.00,
            context: 400_000,
            max_output_tokens: 272_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: false,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-5-codex",
            display_name: "GPT-5-Codex",
            family: "GPT-5 Codex",
            description: "GPT-5-based Codex model optimized for agentic coding environments.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 1.25,
            output_cost: 10.00,
            cached_input_cost: 0.125,
            context: 400_000,
            max_output_tokens: 128_000,
            knowledge_cutoff: "2024-09-30",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-4.1-nano",
            display_name: "GPT-4.1 nano",
            family: "GPT-4.1",
            description: "Fastest GPT-4.1 variant.",
            status: "deprecated",
            release_stage: "deprecated",
            aliases: ["gpt-4.1-nano-2025-04-14"],
            input_cost: 0.10,
            output_cost: 0.40,
            cached_input_cost: 0.025,
            context: 1_047_576,
            max_output_tokens: 32_768,
            knowledge_cutoff: "2024-06-01",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch", "fine-tuning"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-4.1-mini",
            display_name: "GPT-4.1 mini",
            family: "GPT-4.1",
            description: "Smaller, faster GPT-4.1 release.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-4.1-mini-2025-04-14"],
            input_cost: 0.40,
            output_cost: 1.60,
            cached_input_cost: 0.10,
            context: 1_047_576,
            max_output_tokens: 32_768,
            knowledge_cutoff: "2024-06-01",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch", "fine-tuning"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-4.1",
            display_name: "GPT-4.1",
            family: "GPT-4.1",
            description: "Smartest non-reasoning GPT-4.1 release.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-4.1-2025-04-14"],
            input_cost: 2.00,
            output_cost: 8.00,
            cached_input_cost: 0.50,
            context: 1_047_576,
            max_output_tokens: 32_768,
            knowledge_cutoff: "2024-06-01",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch", "fine-tuning"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-4o-mini",
            display_name: "GPT-4o mini",
            family: "GPT-4o",
            description: "Affordable multimodal GPT-4o mini release.",
            status: "active",
            release_stage: "stable",
            aliases: ["gpt-4o-mini-2024-07-18"],
            input_cost: 0.15,
            output_cost: 0.60,
            cached_input_cost: 0.075,
            context: 128_000,
            max_output_tokens: 16_384,
            knowledge_cutoff: "2023-10-01",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch", "fine-tuning"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gpt-4o",
            display_name: "GPT-4o",
            family: "GPT-4o",
            description: "Versatile multimodal GPT-4o flagship outside the o-series.",
            status: "deprecated",
            release_stage: "deprecated",
            aliases: ["gpt-4o-2024-11-20", "gpt-4o-2024-08-06", "gpt-4o-2024-05-13"],
            input_cost: 2.50,
            output_cost: 10.00,
            cached_input_cost: 1.25,
            context: 128_000,
            max_output_tokens: 16_384,
            knowledge_cutoff: "2023-10-01",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch", "fine-tuning"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "o3-mini",
            display_name: "o3-mini",
            family: "o3",
            description: "Small reasoning model alternative to o3.",
            status: "deprecated",
            release_stage: "deprecated",
            aliases: ["o3-mini-2025-01-31"],
            input_cost: 1.10,
            output_cost: 4.40,
            cached_input_cost: 0.55,
            context: 200_000,
            max_output_tokens: 100_000,
            knowledge_cutoff: "2023-10-01",
            reasoning: true,
            streaming: true,
            vision: false,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "o4-mini",
            display_name: "o4-mini",
            family: "o4",
            description: "Fast, cost-efficient reasoning model succeeded by GPT-5 mini.",
            status: "deprecated",
            release_stage: "deprecated",
            aliases: ["o4-mini-2025-04-16"],
            input_cost: 1.10,
            output_cost: 4.40,
            cached_input_cost: 0.275,
            context: 200_000,
            max_output_tokens: 100_000,
            knowledge_cutoff: "2024-06-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "o3",
            display_name: "o3",
            family: "o3",
            description: "Well-rounded reasoning model for complex technical work.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["o3-2025-04-16"],
            input_cost: 2.00,
            output_cost: 8.00,
            cached_input_cost: 0.50,
            context: 200_000,
            max_output_tokens: 100_000,
            knowledge_cutoff: "2024-06-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "o3-pro",
            display_name: "o3-pro",
            family: "o3",
            description: "Higher-compute o3 variant for tougher reasoning requests.",
            status: "active",
            release_stage: "stable",
            aliases: ["o3-pro-2025-06-10"],
            input_cost: 20.00,
            output_cost: 80.00,
            context: 200_000,
            max_output_tokens: 100_000,
            knowledge_cutoff: "2024-06-01",
            reasoning: true,
            streaming: false,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: false,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "o1-mini",
            display_name: "o1-mini",
            family: "o1",
            description: "Earlier small o-series reasoning model, retained for compatibility.",
            status: "deprecated",
            release_stage: "deprecated",
            aliases: ["o1-mini-2024-09-12"],
            input_cost: 1.10,
            output_cost: 4.40,
            cached_input_cost: 0.55,
            context: 128_000,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2023-10-01",
            reasoning: true,
            streaming: true,
            vision: false,
            function_calling: false,
            structured_outputs: false,
            tool_use: false,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "o1",
            display_name: "o1",
            family: "o1",
            description: "Previous full o-series reasoning model.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["o1-2024-12-17", "o1-preview", "o1-preview-2024-09-12"],
            input_cost: 15.00,
            output_cost: 60.00,
            cached_input_cost: 7.50,
            context: 200_000,
            max_output_tokens: 100_000,
            knowledge_cutoff: "2023-10-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses", "assistants", "batch"],
            config_support: OPENAI_CONFIG_SUPPORT,
        }),
    ],
    gemini: [
        createModel({
            name: "gemini-2.5-flash-lite",
            display_name: "Gemini 2.5 Flash-Lite",
            family: "Gemini 2.5",
            description: "Fastest and most budget-friendly Gemini 2.5 text model.",
            status: "active",
            release_stage: "stable",
            input_cost: 0.10,
            output_cost: 0.40,
            cached_input_cost: 0.01,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio", "pdf"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gemini-2.5-flash",
            display_name: "Gemini 2.5 Flash",
            family: "Gemini 2.5",
            description: "Best Gemini price-performance model for reasoning-capable, high-volume workloads.",
            status: "active",
            release_stage: "stable",
            input_cost: 0.30,
            output_cost: 2.50,
            cached_input_cost: 0.03,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gemini-2.5-pro",
            display_name: "Gemini 2.5 Pro",
            family: "Gemini 2.5",
            description: "Most advanced stable Gemini reasoning model for complex coding and analysis.",
            status: "active",
            release_stage: "stable",
            input_cost: 1.25,
            output_cost: 10.00,
            cached_input_cost: 0.125,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio", "pdf"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "gemini-3-flash-preview",
            display_name: "Gemini 3 Flash Preview",
            family: "Gemini 3",
            description: "Preview Gemini 3 flash model for speed, scale, and frontier intelligence.",
            status: "preview",
            release_stage: "preview",
            input_cost: 0.50,
            output_cost: 3.00,
            cached_input_cost: 0.05,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio", "pdf"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gemini-3-pro-preview",
            display_name: "Gemini 3 Pro Preview",
            family: "Gemini 3",
            description: "Preview Gemini 3 pro model for advanced reasoning and agentic coding.",
            status: "preview",
            release_stage: "preview",
            input_cost: 2.00,
            output_cost: 12.00,
            cached_input_cost: 0.20,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio", "pdf"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gemini-2.5-flash-lite-preview-09-2025",
            display_name: "Gemini 2.5 Flash-Lite Preview",
            family: "Gemini 2.5",
            description: "Preview 2.5 Flash-Lite release.",
            status: "preview",
            release_stage: "preview",
            input_cost: 0.10,
            output_cost: 0.40,
            cached_input_cost: 0.01,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio", "pdf"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gemini-2.5-flash-preview-09-2025",
            display_name: "Gemini 2.5 Flash Preview",
            family: "Gemini 2.5",
            description: "Preview 2.5 Flash release for production-eligible preview testing.",
            status: "preview",
            release_stage: "preview",
            input_cost: 0.30,
            output_cost: 2.50,
            cached_input_cost: 0.03,
            context: 1_048_576,
            max_output_tokens: 65_536,
            knowledge_cutoff: "2025-01",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gemini-2.0-flash-lite",
            display_name: "Gemini 2.0 Flash-Lite",
            family: "Gemini 2.0",
            description: "Earlier low-cost Gemini 2.0 Flash-Lite release.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gemini-2.0-flash-lite-001"],
            input_cost: 0.075,
            output_cost: 0.30,
            context: 1_048_576,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-08",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: false,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gemini-2.0-flash",
            display_name: "Gemini 2.0 Flash",
            family: "Gemini 2.0",
            description: "Earlier Gemini 2.0 workhorse release.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["gemini-2.0-flash-001", "gemini-2.0-flash-exp"],
            input_cost: 0.10,
            output_cost: 0.40,
            cached_input_cost: 0.025,
            context: 1_048_576,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-08",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
        }),
        createModel({
            name: "gemini-1.5-pro",
            display_name: "Gemini 1.5 Pro",
            family: "Gemini 1.5",
            description: "Long-context Gemini 1.5 Pro release retained for compatibility.",
            status: "retired",
            release_stage: "retired",
            aliases: ["gemini-1.5-pro-latest", "gemini-1.5-pro-001", "gemini-1.5-pro-002"],
            input_cost: 1.25,
            output_cost: 5.00,
            cached_input_cost: 0.3125,
            context: 2_097_152,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-09",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
            retirement_date: "2025-09-24",
        }),
        createModel({
            name: "gemini-1.5-flash",
            display_name: "Gemini 1.5 Flash",
            family: "Gemini 1.5",
            description: "Retired Gemini 1.5 Flash release kept for compatibility metadata.",
            status: "retired",
            release_stage: "retired",
            aliases: ["gemini-1.5-flash-latest", "gemini-1.5-flash-001", "gemini-1.5-flash-002"],
            input_cost: 0.075,
            output_cost: 0.30,
            cached_input_cost: 0.01875,
            context: 1_048_576,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-09",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
            retirement_date: "2025-09-24",
        }),
        createModel({
            name: "gemini-1.5-flash-8b",
            display_name: "Gemini 1.5 Flash-8B",
            family: "Gemini 1.5",
            description: "Retired small Gemini 1.5 Flash model for lower-intelligence workloads.",
            status: "retired",
            release_stage: "retired",
            aliases: ["gemini-1.5-flash-8b-latest", "gemini-1.5-flash-8b-001"],
            input_cost: 0.0375,
            output_cost: 0.15,
            cached_input_cost: 0.01,
            context: 1_048_576,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-10",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image", "video", "audio"],
            output_modalities: ["text"],
            supported_endpoints: ["generateContent"],
            config_support: GEMINI_CONFIG_SUPPORT,
            retirement_date: "2025-09-24",
        }),
    ],
    deepseek: [
        createModel({
            name: "deepseek-chat",
            display_name: "DeepSeek Chat",
            family: "DeepSeek V3",
            description: "Current DeepSeek chat alias pointing to the latest V3 snapshot.",
            status: "active",
            release_stage: "stable",
            aliases: ["deepseek-v3-0324"],
            input_cost: 0.27,
            output_cost: 1.10,
            cached_input_cost: 0.07,
            context: 64_000,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-11",
            reasoning: false,
            streaming: true,
            vision: false,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions"],
            config_support: DEEPSEEK_CHAT_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "deepseek-reasoner",
            display_name: "DeepSeek Reasoner",
            family: "DeepSeek R1",
            description: "Current DeepSeek reasoner alias pointing to the latest R1 snapshot.",
            status: "active",
            release_stage: "stable",
            aliases: ["deepseek-r1"],
            input_cost: 0.55,
            output_cost: 2.19,
            cached_input_cost: 0.14,
            context: 64_000,
            max_output_tokens: 32_768,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: false,
            function_calling: false,
            structured_outputs: false,
            tool_use: false,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions"],
            config_support: DEEPSEEK_REASONER_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "deepseek-v3-0324",
            display_name: "DeepSeek V3 (0324)",
            family: "DeepSeek V3",
            description: "March 2025 DeepSeek V3 snapshot with improved instruction following.",
            status: "active",
            release_stage: "stable",
            input_cost: 0.27,
            output_cost: 1.10,
            cached_input_cost: 0.07,
            context: 64_000,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-11",
            reasoning: false,
            streaming: true,
            vision: false,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions"],
            config_support: DEEPSEEK_CHAT_CONFIG_SUPPORT,
        }),
        createModel({
            name: "deepseek-v3",
            display_name: "DeepSeek V3",
            family: "DeepSeek V3",
            description: "Original December 2024 DeepSeek V3 release.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 0.27,
            output_cost: 1.10,
            cached_input_cost: 0.07,
            context: 64_000,
            max_output_tokens: 8_192,
            knowledge_cutoff: "2024-11",
            reasoning: false,
            streaming: true,
            vision: false,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions"],
            config_support: DEEPSEEK_CHAT_CONFIG_SUPPORT,
        }),
        createModel({
            name: "deepseek-r1",
            display_name: "DeepSeek R1",
            family: "DeepSeek R1",
            description: "Original January 2025 DeepSeek R1 reasoning release.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 0.55,
            output_cost: 2.19,
            cached_input_cost: 0.14,
            context: 64_000,
            max_output_tokens: 32_768,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: false,
            function_calling: false,
            structured_outputs: false,
            tool_use: false,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions"],
            config_support: DEEPSEEK_REASONER_CONFIG_SUPPORT,
        }),
    ],
    grok: [
        createModel({
            name: "grok-4-1-fast",
            display_name: "Grok 4.1 Fast",
            family: "Grok 4.1",
            description: "Current cost-efficient Grok reasoning model for fast coding and agent loops.",
            status: "active",
            release_stage: "stable",
            aliases: ["grok-4-1-fast-reasoning", "grok-4-fast-reasoning"],
            input_cost: 0.20,
            output_cost: 0.50,
            context: 2_000_000,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_REASONING_CONFIG_SUPPORT,
            current: true,
            recommended: true,
        }),
        createModel({
            name: "grok-4.20-reasoning",
            display_name: "Grok 4.20 Reasoning",
            family: "Grok 4.20",
            description: "Newest xAI flagship reasoning model with strong prompt adherence and tool use.",
            status: "active",
            release_stage: "stable",
            aliases: ["grok-4.20"],
            input_cost: 0,
            output_cost: 0,
            context: 2_000_000,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_REASONING_CONFIG_SUPPORT,
            current: true,
            recommended: true,
            pricing_available: false,
        }),
        createModel({
            name: "grok-code-fast-1",
            display_name: "Grok Code Fast 1",
            family: "Grok Code",
            description: "Fast Grok model optimized for code-heavy workloads.",
            status: "active",
            release_stage: "stable",
            input_cost: 0.20,
            output_cost: 1.50,
            context: 256_000,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_REASONING_CONFIG_SUPPORT,
        }),
        createModel({
            name: "grok-4-fast-non-reasoning",
            display_name: "Grok 4 Fast Non-Reasoning",
            family: "Grok 4 Fast",
            description: "Legacy non-reasoning Grok 4 Fast release retained for compatibility.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 0.20,
            output_cost: 0.50,
            context: 2_000_000,
            knowledge_cutoff: "2024-11",
            reasoning: false,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_NON_REASONING_CONFIG_SUPPORT,
        }),
        createModel({
            name: "grok-4-0709",
            display_name: "Grok 4 (0709)",
            family: "Grok 4",
            description: "Earlier full Grok 4 release.",
            status: "legacy",
            release_stage: "stable",
            aliases: ["grok-4"],
            input_cost: 3.00,
            output_cost: 15.00,
            context: 256_000,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_REASONING_CONFIG_SUPPORT,
        }),
        createModel({
            name: "grok-3-mini",
            display_name: "Grok 3 Mini",
            family: "Grok 3",
            description: "Earlier small Grok 3 reasoning model.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 0.30,
            output_cost: 0.50,
            context: 131_072,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: false,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_REASONING_CONFIG_SUPPORT,
        }),
        createModel({
            name: "grok-3",
            display_name: "Grok 3",
            family: "Grok 3",
            description: "Earlier full Grok 3 model.",
            status: "legacy",
            release_stage: "stable",
            input_cost: 3.00,
            output_cost: 15.00,
            context: 131_072,
            knowledge_cutoff: "2024-11",
            reasoning: true,
            streaming: true,
            vision: true,
            function_calling: true,
            structured_outputs: true,
            tool_use: true,
            prompt_caching: true,
            input_modalities: ["text", "image"],
            output_modalities: ["text"],
            supported_endpoints: ["chat/completions", "responses"],
            config_support: GROK_REASONING_CONFIG_SUPPORT,
        }),
    ],
}

export const providerModels: Models = {
    anthropic: providerModelsByName.anthropic,
    openai: providerModelsByName.openai,
    gemini: providerModelsByName.gemini,
    grok: providerModelsByName.grok,
}

export const models = providerModels

function createConfigSupport(overrides: Partial<ModelConfigSupport>): ModelConfigSupport {
    return {
        system_prompt: false,
        temperature: false,
        max_tokens: false,
        top_p: false,
        top_k: false,
        frequency_penalty: false,
        presence_penalty: false,
        stop_sequences: false,
        n: false,
        ...overrides,
    }
}

function createModel(model: ModelInfo): ModelInfo {
    return {
        aliases: [],
        cached_input_cost: undefined,
        max_output_tokens: undefined,
        knowledge_cutoff: undefined,
        current: false,
        recommended: false,
        pricing_available: true,
        retirement_date: undefined,
        ...model,
    }
}
