//
// BugHunter.ts
//
// Rueter AI — Pipelines
//
// Scans a source directory for logic bugs and security vulnerabilities,
// producing a RueterBugReport.md with per-file findings.
//

import * as nodePath from "node:path"

import {
    DebugModel,
    SecurityAuditorModel,
} from "../models/SpecialModels.js"

import {
    ask, log, timestamp,
    readFileSafe, writeFileSafe, collectSourceFiles,
    type ProgressCallback,
} from "./_shared.js"

// ─── Config ───────────────────────────────────────────────────────────────────

export interface BugHunterConfig {
    /** xAI API key */
    apiKey: string
    /** Directory to scan for source files */
    sourceDir: string
    /** Path for the bug report file (default: ./RueterBugReport.md) */
    reportPath?: string
    /** File extensions to scan (default: [".ts", ".js", ".py", ".go"]) */
    extensions?: string[]
    /** Called after each step with a status message */
    onProgress?: ProgressCallback
}

// ─── Internal Types ───────────────────────────────────────────────────────────

interface BugFinding {
    filePath: string
    logicIssues: string
    securityIssues: string
    hasIssues: boolean
}

// ─── Report Builder ───────────────────────────────────────────────────────────

function buildBugReportMd(sourceDir: string, findings: BugFinding[], isComplete: boolean): string {
    const withIssues = findings.filter(f => f.hasIssues)
    const statusLine = isComplete
        ? `Scan complete · ${findings.length} files scanned · ${withIssues.length} files with issues`
        : `Scan in progress · ${findings.length} files scanned so far…`

    const findingBlocks = findings.map(f => {
        const rel = nodePath.relative(sourceDir, f.filePath)
        if (!f.hasIssues) return `### ✅ \`${rel}\`\n\nNo issues found.`
        return [
            `### ⚠️ \`${rel}\``,
            "", "#### Logic & Runtime Issues", f.logicIssues,
            "", "#### Security Issues", f.securityIssues,
        ].join("\n")
    }).join("\n\n---\n\n")

    return [
        "# RueterBugReport",
        `> Generated by Rueter AI · ${timestamp()}`,
        `> Source: \`${sourceDir}\``,
        "", "## Summary", statusLine,
        "", "## Findings", "",
        findingBlocks || "_No files scanned yet._",
        "",
    ].join("\n")
}

// ─── Workflow ─────────────────────────────────────────────────────────────────

/**
 * Scans a source directory for logic bugs and security vulnerabilities,
 * producing a comprehensive RueterBugReport.md with per-file findings.
 *
 * Pipeline (per file):
 *   1. Logic & runtime analysis → DebugModel        (parallel per file)
 *   2. Security analysis → SecurityAuditorModel     (parallel per file)
 *   3. Append findings to report after each scan
 */
export async function BugHunterWorkflow(config: BugHunterConfig): Promise<void> {
    const {
        apiKey,
        sourceDir,
        reportPath = nodePath.join(process.cwd(), "RueterBugReport.md"),
        extensions = [".ts", ".js", ".py", ".go"],
        onProgress,
    } = config

    const debugger_  = DebugModel(apiKey)
    const secAuditor = SecurityAuditorModel(apiKey)

    log(onProgress, `Collecting source files in ${sourceDir}…`)
    const files = await collectSourceFiles(sourceDir, extensions)

    if (files.length === 0) {
        throw new Error(`No files found in "${sourceDir}" with extensions: ${extensions.join(", ")}`)
    }

    log(onProgress, `Found ${files.length} files to scan.`)

    const findings: BugFinding[] = []
    await writeFileSafe(reportPath, buildBugReportMd(sourceDir, findings, false))

    for (let i = 0; i < files.length; i++) {
        const filePath = files[i]
        const relPath  = nodePath.relative(sourceDir, filePath)
        log(onProgress, `  [${i + 1}/${files.length}] Scanning ${relPath}…`)

        const content = await readFileSafe(filePath)
        if (!content || content.trim().length === 0) {
            findings.push({ filePath, logicIssues: "File is empty.", securityIssues: "N/A", hasIssues: false })
            continue
        }

        const fileContext = `// FILE: ${relPath}\n${content}`
        const [logicIssues, securityIssues] = await Promise.all([
            ask(debugger_,  `Analyze this file for logic errors, runtime bugs, and incorrect behavior:\n\n${fileContext}`),
            ask(secAuditor, fileContext),
        ])

        const issueKeywords = /SEVERITY|ROOT CAUSE|bug|error|vulnerability|issue|risk|flaw|insecure|injection/i
        findings.push({ filePath, logicIssues, securityIssues, hasIssues: issueKeywords.test(logicIssues) || issueKeywords.test(securityIssues) })
        await writeFileSafe(reportPath, buildBugReportMd(sourceDir, findings, false))
    }

    await writeFileSafe(reportPath, buildBugReportMd(sourceDir, findings, true))

    const withIssues = findings.filter(f => f.hasIssues).length
    log(onProgress, `\n✅ Scan complete — ${files.length} files scanned, ${withIssues} with issues`)
    log(onProgress, `Report: ${reportPath}`)
}
