//
// CodeRefactor.ts
//
// Rueter AI — Pipelines
//
// Refactors every source file in a directory, writing improved versions to an
// output directory while optionally generating tests for each one.
//

import * as nodePath from "node:path"

import {
    instantiateSpecialPreset,
    RefactorPreset,
    SecurityAuditorPreset,
    TestGeneratorPreset,
} from "../models/SpecialModels.js"

import {
    ask, log, timestamp,
    readFileSafe, writeFileSafe, collectSourceFiles,
    type ProgressCallback,
} from "./_shared.js"

// ─── Config ───────────────────────────────────────────────────────────────────

export interface CodeRefactorConfig {
    /** xAI API key */
    apiKey: string
    /** Directory containing source files to refactor */
    sourceDir: string
    /** Directory where refactored files will be written */
    outputDir: string
    /** Generate a test file alongside each refactored file (default: true) */
    generateTests?: boolean
    /** Path for the refactor report (default: ./RueterRefactor.md) */
    reportPath?: string
    /** File extensions to include (default: [".ts", ".js"]) */
    extensions?: string[]
    /** Called after each step with a status message */
    onProgress?: ProgressCallback
}

// ─── Internal Types ───────────────────────────────────────────────────────────

interface RefactorResult {
    filePath: string
    outputPath: string
    testPath?: string
    securityIssues: string
    hasSecurityIssues: boolean
}

// ─── Report Builder ───────────────────────────────────────────────────────────

function buildRefactorReportMd(
    sourceDir: string,
    outputDir: string,
    results: RefactorResult[],
    generateTests: boolean
): string {
    const withIssues = results.filter(r => r.hasSecurityIssues)

    const resultBlocks = results.map(r => {
        const relSource = nodePath.relative(sourceDir, r.filePath)
        const relOutput = nodePath.relative(outputDir, r.outputPath)
        const testLine  = r.testPath ? `\n**Tests:** \`${nodePath.relative(outputDir, r.testPath)}\`` : ""
        const secBlock  = r.hasSecurityIssues
            ? `\n\n**Security findings:**\n\`\`\`\n${r.securityIssues}\n\`\`\``
            : "\n\n**Security:** No issues found."
        return [`### ✅ \`${relSource}\``, `**Output:** \`${relOutput}\`${testLine}`, secBlock].join("\n")
    }).join("\n\n---\n\n")

    return [
        "# RueterRefactor",
        `> Generated by Rueter AI · ${timestamp()}`,
        `> Source: \`${sourceDir}\` → Output: \`${outputDir}\``,
        "", "## Summary",
        `- **Files refactored:** ${results.length}`,
        generateTests ? `- **Test files generated:** ${results.filter(r => r.testPath).length}` : "",
        `- **Files with security issues:** ${withIssues.length}`,
        "", "## Results", "",
        resultBlocks || "_No files processed yet._",
        "",
    ].filter(line => line !== "").join("\n")
}

// ─── Workflow ─────────────────────────────────────────────────────────────────

/**
 * Refactors every source file in a directory, writing improved versions to an
 * output directory while optionally generating a test file for each one.
 *
 * Pipeline (per file):
 *   1. Refactor → RefactorPreset
 *   2. Security check → SecurityAuditorPreset
 *   3. (Optional) Generate tests → TestGeneratorPreset
 */
export async function CodeRefactorWorkflow(config: CodeRefactorConfig): Promise<void> {
    const {
        apiKey,
        sourceDir,
        outputDir,
        generateTests = true,
        reportPath    = nodePath.join(process.cwd(), "RueterRefactor.md"),
        extensions    = [".ts", ".js"],
        onProgress,
    } = config

    const refactorer = instantiateSpecialPreset(apiKey, RefactorPreset)
    const secAuditor = instantiateSpecialPreset(apiKey, SecurityAuditorPreset)
    const testGen    = instantiateSpecialPreset(apiKey, TestGeneratorPreset)

    log(onProgress, `Collecting source files in ${sourceDir}…`)
    const files = await collectSourceFiles(sourceDir, extensions)

    if (files.length === 0) {
        throw new Error(`No files found in "${sourceDir}" with extensions: ${extensions.join(", ")}`)
    }

    log(onProgress, `Found ${files.length} files to refactor.`)

    const results: RefactorResult[] = []

    for (let i = 0; i < files.length; i++) {
        const filePath       = files[i]
        const relPath        = nodePath.relative(sourceDir, filePath)
        const outputFilePath = nodePath.join(outputDir, relPath)
        log(onProgress, `  [${i + 1}/${files.length}] Refactoring ${relPath}…`)

        const content = await readFileSafe(filePath)
        if (!content || content.trim().length === 0) {
            log(onProgress, `    Skipped (empty file)`)
            continue
        }

        try {
            const refactored = await ask(
                refactorer,
                `Refactor the following file. Preserve exact runtime behavior.\n\n// FILE: ${relPath}\n${content}`
            )

            const secAudit          = await ask(secAuditor, `// FILE: ${relPath}\n${refactored}`)
            const hasSecurityIssues = /SEVERITY|vulnerability|injection|insecure|flaw/i.test(secAudit)

            await writeFileSafe(outputFilePath, refactored)

            const result: RefactorResult = { filePath, outputPath: outputFilePath, securityIssues: secAudit, hasSecurityIssues }

            if (generateTests) {
                log(onProgress, `    Generating tests for ${relPath}…`)
                const tests    = await ask(testGen, `Generate comprehensive tests for the following code.\n\n// FILE: ${relPath}\n${refactored}`)
                const ext      = nodePath.extname(outputFilePath)
                const testPath = outputFilePath.slice(0, -ext.length) + ".test" + ext
                await writeFileSafe(testPath, tests)
                result.testPath = testPath
            }

            results.push(result)
            log(onProgress, `    ✅ ${relPath}`)

        } catch (err) {
            log(onProgress, `    ❌ Failed: ${relPath} — ${err instanceof Error ? err.message : String(err)}`)
        }

        await writeFileSafe(reportPath, buildRefactorReportMd(sourceDir, outputDir, results, generateTests))
    }

    await writeFileSafe(reportPath, buildRefactorReportMd(sourceDir, outputDir, results, generateTests))

    const testCount = results.filter(r => r.testPath).length
    log(onProgress, `\n✅ Done — ${results.length} files refactored${generateTests ? `, ${testCount} test files generated` : ""}`)
    log(onProgress, `Output:  ${outputDir}`)
    log(onProgress, `Report:  ${reportPath}`)
}
